version: "3"

services:
  neo4j:
    #neo4j:4.4.2-community
    #neo4j:4.4.2-enterprise
    image: neo4j:4.4.2-community
    container_name: neo4j
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - NEO4J_AUTH=neo4j/topsec518
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./conf:/var/lib/neo4j/conf
      - ./logs:/var/lib/neo4j/logs
      - /etc/localtime:/etc/localtime:ro