version: "3"

services:
  neo4j:
    #neo4j:4.1.4-community
    #neo4j:4.1.4-enterprise
    image: neo4j:4.1.4-community
    container_name: neo4j
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./conf:/conf
      - /etc/localtime:/etc/localtime:ro