apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///run/cri-dockerd.sock
  imagePullPolicy: IfNotPresent
---

apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
clusterName: yasin-cluster
imageRepository: registry.aliyuncs.com/google_containers
kubernetesVersion: v1.28.2
apiServer:
  certSANs:
  - "192.168.0.1"
controlPlaneEndpoint: "192.168.0.1:6443"
networking:
  serviceSubnet: "10.1.0.0/16"
  podSubnet: "10.244.0.0/16"