mode: product
replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  nodePort: 30422
  externalTrafficPolicy: Local
env:
  - name: TZ
    value: Asia/Shanghai
volumeMounts:
  - name: timezone
    mountPath: /etc/localtime
    readOnly: true
volumes:
  - name: timezone
    hostPath:
      path: /etc/localtime
nats:
  nodeName:
  image: nats
  tag: "2.8.4-alpine"