apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      name: tcp
      protocol: TCP
      targetPort: 27017
  {{- if eq .Values.mode "dev" }}
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort
  {{- end }}