version: "2.1"

#### 对应数据文件目录需要UID 1001权限
services:
  clickhouse:
    image: bitnami/clickhouse:22.8.8
    container_name: clickhouse
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - CLICKHOUSE_ADMIN_USER=default
      - CLICKHOUSE_ADMIN_PASSWORD=8123
    volumes:
      - ./config/config.xml:/bitnami/clickhouse/etc/config.xml
      - ./data:/bitnami/clickhouse/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9000:9000"
      - "8123:8123"