apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
  labels:
    app: kafka
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ .Values.kafka.image }}:{{ .Values.kafka.tag }}"
          env:
            {{- include "common.env" . }}
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: 'true'
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: {{ .Values.kafka.cfgAdvertisedListeners }}
          volumeMounts:
            {{- include "common.volumeMounts" . }}
{{/*            - name: data*/}}
{{/*              mountPath: /bitnami/kafka/data*/}}
{{/*              subPath: kafka/data*/}}
      volumes:
        {{- include "common.volumes" . }}