apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      name: tcp
      protocol: TCP
      targetPort: 9092
  {{- if eq .Values.mode "dev" }}
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort
  {{- end }}