apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: tcp
      protocol: TCP
      port: 9092
      targetPort: 9092
  {{- if eq .Values.mode "dev" }}
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort
  {{- end }}