apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-config
  namespace: {{ .Release.Namespace }}
data:
  server.crt: |
{{ .Files.Get "etc/server.crt" | indent 4 }}
  server.key: |
{{ .Files.Get "etc/server.key" | indent 4 }}
#  htpasswd -Bbn yasin yasin3467 > ./etc/htpasswd
  htpasswd: |
{{ .Files.Get "etc/htpasswd" | indent 4 }}
