apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "4"
data:
  server.crt: |
{{ .Files.Get "etc/registry/server.crt" | indent 4 }}
  server.key: |
{{ .Files.Get "etc/registry/server.key" | indent 4 }}
  htpasswd: "yasin:$2y$05$OU/5YXj3W3phRisYSvI6R.HodcKbK.wmkkeHnjW1VVS1SgBaU9eVu"