apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: {{ .Release.Namespace }}
  labels:
    app: registry
spec:
  selector:
    app: registry
  ports:
    - name: tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
  type: NodePort