apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: yasin-app
spec:
  ports:
    - port: 8080
      name: tcp8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30088
  selector:
    app: jenkins
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: yasin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.442-jdk17
        env:
          - name: "GOPROXY"
            value: "https://goproxy.cn,direct"
        volumeMounts:
          - name: data
            mountPath: /var/jenkins_home
            subPath: jenkins_home
          - name: timezone
            mountPath: /etc/localtime
            readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: yasin-cloud
        - name: timezone
          hostPath:
            path: /etc/localtime