apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: yasin-app
spec:
  ports:
    - port: 27017
      name: tcp
      protocol: TCP
      targetPort: 27017
      nodePort: 32017
  selector:
    app: mongo
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: yasin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: bitnami/mongodb:5.0.5
          imagePullPolicy: IfNotPresent
          name: mongo
          env:
            - name: MONGODB_ROOT_USER
              value: root
            - name: MONGODB_ROOT_PASSWORD
              value: Yasin_3467
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - name: data
              mountPath: /bitnami/mongodb/data
              subPath: mongodb/data
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: yasin-cloud
        - name: timezone
          hostPath:
            path: /etc/localtime
