apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: yasin-app
spec:
  ports:
    - port: 443
      name: https
      protocol: TCP
      targetPort: 443
      nodePort: 30443
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  selector:
    app: nginx
  type: NodePort
  externalTrafficPolicy: Cluster
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: yasin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeName: master
      containers:
        - image: bitnami/nginx:1.25.4
          imagePullPolicy: IfNotPresent
          name: nginx
          env:
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - name: config
              mountPath: /opt/bitnami/nginx/conf/nginx.conf
              subPath: nginx.conf
            - name: ca
              mountPath: /home/yasin/nginx/ca
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: ca
          configMap:
            name: nginx-config
            items:
              - key: server.crt
                path: server.crt
              - key: server.key
                path: server.key
        - name: timezone
          hostPath:
            path: /etc/localtime