build:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^feature-.*/'
    - if: '$CI_COMMIT_BRANCH == "develop"'
  tags:
    - ${RUNNER}
  script:
    - make buildi VERSION=${VERSION} ARCH=amd64
    - make buildi VERSION=${VERSION} ARCH=arm64