apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: {{ .Release.Namespace }}
  labels:
    app: nats
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      {{- if .Values.nats.nodeName }}
      nodeName: {{ .Values.nats.nodeName }}
      {{- end }}
      containers:
        - name: nats
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ .Values.nats.image }}:{{ .Values.nats.tag }}"
          env:
            {{- include "common.env" . }}
          volumeMounts:
            {{- include "common.volumeMounts" . }}
            - name: config
              mountPath: /etc/nats/nats-server.conf
              subPath: nats-server.conf
      volumes:
        {{- include "common.volumes" . }}
        - name: config
          configMap:
            name: nats-config
            items:
              - key: nats-server.conf
                path: nats-server.conf