apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: {{ .Release.Namespace }}
  labels:
    app: nats
spec:
  selector:
    app: nats
  ports:
    - port: 4222
      name: tcp
      protocol: TCP
      targetPort: 4222
  {{- if eq .Values.mode "dev" }}
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort
  {{- end }}