apiVersion: v1
kind: Service
metadata:
  name: yasin-nginx
  namespace: yasin-app
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      nodePort: 30443
      protocol: TCP
      targetPort: 443
    - name: http
      port: 80
      nodePort: 30080
      protocol: TCP
      targetPort: 80
  selector:
    app: yasin-nginx


---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: yasin-nginx
  name: yasin-nginx
  namespace: yasin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yasin-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: yasin-nginx
    spec:
      containers:
        - image: nginx:latest
          imagePullPolicy: Always
          name: yasin-nginx
          volumeMounts:
            - name: nginxconf
              mountPath: /etc/nginx/nginx.conf
            - name: timezone
              mountPath: /etc/localtime
      volumes:
        - name: nginxconf
          hostPath:
            path: /Users/yasin/GoWork/yasin/config/kubernetes/nginx/nginx.conf
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai