version: '3'

services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=yasinwu
    volumes:
      - ./data:/bitnami/redis/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6379:6379"
