version: '3'

services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_EMPTY_PASSWORD=yes
      #- REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      #- ${DATA_PATH_HOST}/redis:/bitnami/redis/data
      #- ./conf/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6379:6379"
