kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "etc/**").AsConfig | indent 2 }}
  ca.crt.test: |
{{ .Files.Get "etc/ca/ca.crt" | indent 4 }}