apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "etc/*").AsConfig | indent 2 }}
{{ (.Files.Glob "etc/ca/*").AsConfig | indent 2 }}
{{ (.Files.Glob "etc/conf.d/*").AsConfig | indent 2 }}
