apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.global.pv.name }}
spec:
  capacity:
    storage: {{ .Values.global.pv.storage }}
  volumeMode: Filesystem
  accessModes:
    {{- if eq .Values.global.pv.storageClass "local-path" }}
    - ReadWriteOnce
    {{- else if eq .Values.global.pv.storageClass "nfs" }}
    - ReadWriteMany
    {{- end }}
  persistentVolumeReclaimPolicy: {{ .Values.global.pv.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.global.pv.storageClass }}
  {{- if eq .Values.global.pv.storageClass "local-path" }}
  local:
    path: {{ .Values.global.pv.localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.global.pv.node }}
  {{- else if eq .Values.global.pv.storageClass "nfs" }}
  nfs:
    path: {{ .Values.global.pv.nfsPath }}
    server: {{ .Values.global.pv.nfsServer }}
  {{- end }}