apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.global.localPVC.name}}
spec:
  volumeName: {{.Values.global.localPV.name}}
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1T