apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.pvc.name }}
  namespace: {{ .Release.Namespace }}
spec:
  volumeName: {{ .Values.pv.name }}
  storageClassName: {{ .Values.pv.storageClass }}
  accessModes:
    {{- if eq .Values.pv.storageClass "local-path" }}
    - ReadWriteOnce
    {{- else if eq .Values.pv.storageClass "nfs" }}
    - ReadWriteMany
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.pv.storage }}