apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.crbUser }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch", "update" ]
  - apiGroups: [ "extensions", "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "watch", "list", "update" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "endpoints" ]
    verbs: [ "get", "watch", "list" ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.crbUser }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: User
    name: {{ .Values.crbUser }}
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: {{ .Values.crbUser }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.crbUser }}
  apiGroup: rbac.authorization.k8s.io
---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.crbUser }}
  namespace: {{ .Release.Namespace }}