version: "2.1"

services:
  kibana:
    image: kibana:${VERSION}
    container_name: kibana
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=${TZ}
    volumes:
      - ${DATA_PATH}/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${KIBANA_PORT}:5601"
    networks:
      - elk_net