version: "2.1"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=${TZ}
    volumes:
      - ${DATA_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${NGINX_HTTP_PORT}:80"
    networks:
      - elk_net