apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader
  namespace: reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader
  template:
    metadata:
      labels:
        app: reloader
    spec:
      serviceAccountName: reloader-user
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: reloader
          imagePullPolicy: IfNotPresent
          image: "stakater/reloader:v1.4.4"
          securityContext: { }
#          ports:
#            - name: http
#              containerPort: 9090
          resources:
            requests:
              cpu: "0.1"
              memory: "100Mi"
            limits:
              cpu: "1"
              memory: "200Mi"
#          livenessProbe:
#            httpGet:
#              path: /live
#              port: http
#            initialDelaySeconds: 10
#            periodSeconds: 10
#            timeoutSeconds: 5
#            failureThreshold: 5
#          readinessProbe:
#            httpGet:
#              path: /metrics
#              port: http
#            initialDelaySeconds: 10
#            periodSeconds: 10
#            timeoutSeconds: 5
#            failureThreshold: 5
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  divisor: "1"
                  resource: limits.cpu
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  divisor: "1"
                  resource: limits.memory
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai