apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reloader-role-binding
  namespace: reloader
subjects:
  - kind: ServiceAccount
    name: reloader-user
    namespace: reloader
roleRef:
  kind: ClusterRole
  name: reloader-role
  apiGroup: rbac.authorization.k8s.io