stages:
  - build
  - deploy

build:
   stage: build
   script:
     - cd ${CI_PROJECT_DIR}
     - sh build.sh
   only:
     - cwpp
   artifacts:
     paths:
       - ./dist.tar.gz

deploy:
  stage: deploy
  script:
    - cd ${CI_PROJECT_DIR}
    - sh deploy.sh 127.0.0.1 root root123 /home/work
