stages:
  - "review_code"
  - "unit_test"
  - "build"
  - "push"
  - "deploy"
  - "send_message"

variables:
  APP: "yasin"
  VERSION: "1.0.0"
  RUNNER: "yasin"
  NOTIFICATION: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=yasin"
  COVERPKG: "./pkg/...,./rest/internal/...,./rest/api/config/...,./rest/api/logic/...,./rest/api/svc/...,./rpc/internal/..."
  KUBEREMOTECONFIG: "/home/gitlab-runner/.kube/remote_config"

include:
  - ".gitlab/review_code.yml"
  - ".gitlab/unit_test.yml"
  - ".gitlab/build.yml"
  - ".gitlab/push.yml"
  - ".gitlab/deploy.yml"
  - ".gitlab/send_message.yml"