run:
  skip-files:
    - _test.go
  skip-dirs:
    - test/

linters-settings:
  golint:
    min-confidence: 0
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - funlen
    - goconst
    - gocyclo
    - gofmt
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - gosimple
    - govet
    - rowserrcheck
    - unused
    - varcheck
    - errcheck
    - misspell
    - asciicheck
#    - goimports
#    - golint
#    - lll

service:
  golangci-lint-version: 1.44.2 # use the fixed version to not introduce new linters unexpectedly
