run:
  skip-files:
    - _test.go
  skip-dirs:
    - test/

linters-settings:
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - funlen
    - goconst
    - gocyclo
    - gofmt
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - gosimple
    - govet
    - rowserrcheck
    - unused
    - varcheck
    - errcheck
    - misspell
    - asciicheck
    - revive
    - lll

service:
  golangci-lint-version: 1.44.2 # use the fixed version to not introduce new linters unexpectedly

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: 'SA5008: unknown JSON option ("optional"|"default=|"range=|"options=)'
