apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: NodePort  # 或 LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000  # NodePort 范围 (30000-32767)
    - name: agent
      protocol: TCP
      port: 50000
      targetPort: 50000