version: "3"

services:

  benthos:
    image: jeffail/benthos:4.1.0
    container_name: benthos
    restart: unless-stopped
    privileged: true
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - TZ=Asia/Shanghai
    volumes:
      - ./conf/benthos.yaml:/benthos.yaml
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4195:4195"