version: "2.1"

#### 对应数据文件目录需要UID 1001权限
services:
  kafka:
    image: docker.io/bitnami/kafka:2.8.1
    container_name: kafka
    restart: unless-stopped
    privileged: true
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 #kafka为宿主机IP
      - TZ=${TZ}
    volumes:
      - ./data:/bitnami/kafka/data
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper