apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Chart.Name}}
  name: {{.Chart.Name}}
spec:
  replicas: {{.Values.global.replicaCount}}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:
      containers:
        - image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.global.image.pullPolicy}}
          name: {{.Chart.Name}}
          {{- with .Values.global.env}}
          env:
            {{- toYaml . | nindent 12}}
          {{- end}}
            - name: ALLOW_EMPTY_PASSWORD
              value: 'yes'
          {{- with .Values.global.volumeMounts}}
          volumeMounts:
            {{- toYaml . | nindent 12}}
          {{- end}}
            - name: data
              mountPath: /bitnami/redis/data
              subPath: redis/data
      {{- with .Values.global.volumes}}
      volumes:
        {{- toYaml . | nindent 8}}
      {{- end}}
        - name: data
          persistentVolumeClaim:
            claimName: {{.Values.global.localPVC.name}}