apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  {{- include "metadata.labels" . | indent 2}}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
  {{- include "spec.selector" . | indent 4 }}
  template:
  {{- include "spec.template" . | indent 4 }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          name: {{ .Chart.Name }}
          env:
          {{- with concat .Values.global.env .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- with concat .Values.global.volumeMounts .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- with concat .Values.global.volumes .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "pvc.volumes" . | indent 8 }}