apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  {{- include "nginx.metadata.labels" . | indent 2}}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
  {{- include "nginx.spec.selector" . | indent 4 }}
  template:
  {{- include "nginx.spec.template" . | indent 4 }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          name: {{ .Chart.Name }}
          {{- with .Values.global.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - name: ALLOW_EMPTY_PASSWORD
              value: 'yes'
          {{- with .Values.global.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - name: data
              mountPath: /bitnami/redis/data
              subPath: redis/data
      {{- with .Values.global.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.global.pvc.name }}