apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  {{- include "metadata.labels" . | indent 2}}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: tcp
      protocol: TCP
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Chart.Name }}
  type: {{ .Values.service.type }}