server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: ["http://nginx"]
elasticsearch.username: kibana
elasticsearch.password: yasinwu
i18n.locale: zh-CN
monitoring.kibana.collection.enabled: true
xpack.monitoring.ui.container.elasticsearch.enabled: true
