version: "2.1"

services:
  es-master:
    image: elasticsearch:8.0.0
    container_name: es-master
    restart: unless-stopped
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - TZ=Asia/Shanghai
      - TAKE_FILE_OWNERSHIP=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elasticsearch/master/data:/usr/share/elasticsearch/data
      - ./elasticsearch/master/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/ca/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - /etc/localtime:/etc/localtime:ro
    networks:
      - elk_net

  es-node1:
    image: elasticsearch:8.0.0
    container_name: es-node1
    restart: unless-stopped
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - TZ=Asia/Shanghai
      - TAKE_FILE_OWNERSHIP=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elasticsearch/node1/data:/usr/share/elasticsearch/data
      - ./elasticsearch/node1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/ca/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - /etc/localtime:/etc/localtime:ro
    networks:
      - elk_net