version: "2.1"

services:
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.0.0
    container_name: metricbeat
    restart: unless-stopped
    privileged: true
    user: root
    environment:
      - TZ=Asia/Shanghai
      - setup.kibana.host=kibana:5601
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - ./metricbeat/elasticsearch-xpack.yml:/usr/share/metricbeat/modules.d/elasticsearch-xpack.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    networks:
      - elk_net