apiVersion: v1
kind: Service
metadata:
  labels:
    app: clickhouse
  name: clickhouse
  namespace: yasin-app
spec:
  ports:
    - port: 8123
      name: remote
      protocol: TCP
      targetPort: 8123
      nodePort: 30123
    - port: 9000
      name: localhost
      protocol: TCP
      targetPort: 9000
      nodePort: 30900
  selector:
    app: clickhouse
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clickhouse
  name: clickhouse
  namespace: yasin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - image: bitnami/clickhouse:22.8.8
          imagePullPolicy: IfNotPresent
          name: clickhouse
          env:
            - name: CLICKHOUSE_ADMIN_USER
              value: default
            - name: CLICKHOUSE_ADMIN_PASSWORD
              value: yasin3467
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - name: clickhouse
              mountPath: /bitnami/clickhouse/data
            - name: chconfig
              mountPath: /bitnami/clickhouse/etc/config.xml
            - name: chlog
              mountPath: /var/log/clickhouse-server
            - name: timezone
              mountPath: /etc/localtime
      volumes:
        - name: clickhouse
          hostPath:
            path: /home/yasin/kubernetes/clickhouse
        - name: chconfig
          hostPath:
            path: /config-cbb/clickhouse/config.xml
        - name: chlog
          hostPath:
            path: /home/yasin/kubernetes/clickhouse/log
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
