apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: yasin-app
spec:
  ports:
    - port: 9092
      name: remote
      protocol: TCP
      targetPort: 9092
      nodePort: 30992
  selector:
    app: kafka
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: yasin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - image: bitnami/kafka:3.5.0
          imagePullPolicy: IfNotPresent
          name: kafka
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: 'true'
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://192.168.0.1:9092
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka
              subPath: kafka
            - name: timezone
              mountPath: /etc/localtime
      volumes:
        - name: data
          hostPath:
            path: /data/kafka
        - name: timezone
          hostPath:
            path: /etc/localtime
