apiVersion: v1
kind: Namespace
metadata:
  name: yasin-app
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana
  namespace: yasin-app
spec:
  ports:
    - port: 5601
      name: tcp5601
      protocol: TCP
      targetPort: 5601
      nodePort: 30561
  selector:
    app: kibana
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
  name: kibana
  namespace: yasin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - image: kibana:8.0.0
          imagePullPolicy: IfNotPresent
          name: kibana
          env:
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - name: config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: kibana-config
            items:
              - key: kibana.yml
                path: kibana.yml
        - name: timezone
          hostPath:
            path: /etc/localtime