version: '3.1'

services:

  mysql:
    image: mysql:5.7.37
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "yasinwu"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
