apiVersion: v1
kind: PersistentVolume
metadata:
  name: yasin-cloud
spec:
  capacity:
    storage: 1T
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/yasin/data
    server: 192.168.0.1
