kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: yasin-local-pvc
  namespace: yasin-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: openebs-hostpath
  volumeMode: Filesystem