mode: product
replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  nodePort: 30379
  externalTrafficPolicy: Local
env:
  - name: TZ
    value: Asia/Shanghai
volumeMounts:
  - name: timezone
    mountPath: /etc/localtime
    readOnly: true
volumes:
  - name: timezone
    hostPath:
      path: /etc/localtime
redis:
  nodeName:
  image: bitnami/redis
  tag: "6.2"
  password: