version: '3.1'

services:

  mongo:
    image: mongo:4.4.13
    container_name: mongo
    restart: unless-stopped
    privileged: true
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: yasin3467
    volumes:
      - /etc/localtime:/etc/localtime:ro
