version: '3.1'

services:

  mongo:
    image: mongo:5.0.5
    container_name: mongo
    restart: unless-stopped
    privileged: true
    ports:
      - "27017:27017"
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=yasin3467
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data/db
