apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: yasin-app
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30920
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: yasin-app
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
        - name: sysctl
          imagePullPolicy: IfNotPresent
          image: busybox:latest
          securityContext:
            privileged: true
          command: [ "sysctl","-w","vm.max_map_count=262144" ]
      containers:
        - name: elasticsearch
          imagePullPolicy: IfNotPresent
          image: elasticsearch:8.0.0
          env:
            - name: TAKE_FILE_OWNERSHIP
              value: 'true'
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
              subPath: elasticsearch/data
            - name: data
              mountPath: /usr/share/elasticsearch/backup
              subPath: elasticsearch/backup
            - name: config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            - name: config
              mountPath: /usr/share/elasticsearch/config/elastic-certificates.p12
              subPath: elastic-certificates.p12
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: yasin-cloud
        - name: config
          configMap:
            name: elasticsearch-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
              - key: elastic-certificates.p12
                path: elastic-certificates.p12
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai