#!/bin/bash

commit=`cat $1`

#username=`git config user.name`
#email=`git config user.email`

## 判断是否为公司邮箱，且前缀是否为username
#if [ "$email" != "$username@topsec.com.cn" ]; then
#	echo "请检查git用户名和邮箱配置是否正确"
#	echo ""
#	echo "请设置git用户名：git config --global user.name [邮箱前缀]"
#	echo "请设置git用户邮箱: git config --global user.email [公司邮箱]"
#	echo ""
#	exit 1
#fi

# 按模板检查header行 https://doc.repo.cloud.io/DEVFLOW/VCS/gitlab.html#commit-message
types="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|secure|release)(\(.+\))?: .{1,80}|^Merge branch(.*)"
if [[ ! $commit =~ $types ]]
then
	echo "commit信息不合规。"
	echo ""
	echo "commit标题格式: <type>(<scope>): <subject>"
	echo ""
	echo "type:"
        echo "  feat: 新增功能"
        echo "  fix:  修复bug"
        echo "  docs: 更新文档"
        echo "  style: 优化代码格式"
        echo "  refactor: 重构"
        echo "  perf: 性能优化"
        echo "  test: 增加测试文件"
        echo "  build: 增加修改构建工具"
        echo "  ci: 修改ci脚本"
        echo "  chore: 其它"
        echo "  revert: 撤销某次提交"
        echo "  secure: 安全更新漏洞修复"
        echo "  release: 发布"
	echo ""
	echo "scope[可选]: 本次提交影响的范围。"
	echo ""
	echo "subject: 简要的描述信息，长度10~80。"
	echo ""
	echo "如: feat(logx): 增加一种基于context记录日志的方法"
	echo ""
	echo "更多详细信息请参考: https://doc.repo.cloud.io/DEVFLOW/VCS/gitlab.html#commit-message"
	exit 1
fi

