#!/bin/bash

# shellcheck disable=SC2006
# shellcheck disable=SC2086
commit=`cat $1`

types="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|release)(\(.+\))?: .{1,80}"
if [[ ! $commit =~ $types ]]
then
	echo "commit信息不合规。"
	echo ""
	echo "commit标题格式: <type>(<scope>): <subject>"
	echo ""
	echo "type:"
        echo "  feat: 新增功能"
        echo "  fix:  修复bug"
        echo "  docs: 更新文档"
        echo "  style: 优化代码格式"
        echo "  refactor: 重构"
        echo "  perf: 性能优化"
        echo "  test: 增加测试文件"
        echo "  build: 增加修改构建工具"
        echo "  ci: 修改ci脚本"
        echo "  chore: 其它"
        echo "  revert: 撤销某次提交"
        echo "  release: 发布"
	echo ""
	echo "scope[可选]: 本次提交影响的范围。"
	echo ""
	echo "subject: 简要的描述信息，长度10~80。"
	echo ""
	echo "如: feat(logx): 增加一种基于context记录日志的方法"
	exit 1
fi

