#!/bin/sh

# shellcheck disable=SC2086
set -e

STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

if [ "$STAGED_GO_FILES" != "" ]; then
	golangci-lint run
	for file in $STAGED_GO_FILES; do
		if [ -f $file ]; then
			go fmt $file
			git add $file
		fi
	done
fi
