version: '2.1'

services:

  mysql:
    image: mysql:5.7.37
    container_name: mysql
    restart: unless-stopped
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: "yasinwu"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

