kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: yasin-app
  name: yasin-user
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch", "update" ]
  - apiGroups: [ "extensions", "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "watch", "list", "update" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch" ]

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: yasin-user
  namespace: yasin-app

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: yasin-user
  namespace: yasin-app
subjects:
  - kind: User
    name: yasin-user
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: yasin-user
    namespace: yasin-app
roleRef:
  kind: Role
  name: yasin-user
  apiGroup: rbac.authorization.k8s.io