# 生成SSH密钥: ssh-keygen -t ed25519 -f /var/jenkins_home/.ssh/id_ed25519
# 报错:Permissions 0660 for '/var/jenkins_home/.ssh/id_ed25519' are too open, chmod 600 id_ed25519
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      securityContext:
        fsGroup: 993 # docker用户组 more /etc/group |grep docker
      {{- if .Values.hostAliases }}
      hostAliases:
        {{- with .Values.hostAliases }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      initContainers:
        - name: fix-ssh-permissions
          image: {{ .Values.busybox.image }}:{{ .Values.busybox.tag }}
          imagePullPolicy: IfNotPresent
          command: [ 'sh', '-c', 'chmod 600 /var/jenkins_home/.ssh/id_ed25519' ]
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      containers:
        - name: jenkins
          image: {{ .Values.jenkins.image }}:{{ .Values.jenkins.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPTS
              value: "-Dhudson.model.UpdateCenter.never=true"
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home #admin password ./secrets/initialAdminPassword
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: docker-bin
              mountPath: /usr/bin/docker
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: docker-bin
          hostPath:
            path: /usr/bin/docker
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai