apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: jenkins
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.jenkins.httpNodePort }}
    - name: agent
      protocol: TCP
      port: 50000
      targetPort: 50000
  type: NodePort
